<?php
require_once __DIR__ . '/app/layout.php';
$db = db(); $store = current_store($db); $route = $_GET['r'] ?? '';

function cart_rows(PDO $db, array $store): array {
    $cart = cart(); if (!$cart) return [];
    $ids = array_map('intval', array_keys($cart)); $marks = implode(',', array_fill(0, count($ids), '?'));
    $stmt=$db->prepare("SELECT * FROM products WHERE store_id=? AND id IN ($marks) AND is_active=1"); $stmt->execute(array_merge([(int)$store['id']], $ids));
    $products=[]; foreach($stmt->fetchAll() as $product){ $quantity=max(1,min(99,(int)$cart[$product['id']])); $product['quantity']=$quantity; $product['line_total']=$product['price']*$quantity; $products[]=$product; } return $products;
}
function coupon_discount(PDO $db, array $store, float $subtotal): array {
    $code=strtoupper(trim($_SESSION['coupon_code'] ?? '')); if(!$code) return [0,null];
    $stmt=$db->prepare("SELECT * FROM coupons WHERE store_id=? AND code=? AND is_active=1");$stmt->execute([(int)$store['id'],$code]);$coupon=$stmt->fetch();
    if(!$coupon || $subtotal < (float)$coupon['minimum_order']) return [0,null];
    $discount=$coupon['discount_type']==='percent' ? $subtotal*((float)$coupon['discount_value']/100) : (float)$coupon['discount_value']; return [min($subtotal,$discount),$coupon];
}
function product_card(array $store, array $product): string {
    $image=$product['image'] ? '<img src="'.e($product['image']).'" alt="'.e($product['name']).'">' : '<span class="image-placeholder">Product image</span>';
    return '<article class="product-card"><a class="product-image" href="'.store_url($store,'product',['slug'=>$product['slug']]).'">'.$image.'</a><div><h3><a href="'.store_url($store,'product',['slug'=>$product['slug']]).'">'.e($product['name']).'</a></h3><p>'.money((float)$product['price']).'</p><form method="post" action="'.store_url($store,'cart').'">'.csrf_field().'<input type="hidden" name="action" value="cart_add"><input type="hidden" name="product_id" value="'.(int)$product['id'].'"><input type="hidden" name="return" value="'.e(store_url($store,'shop')).'"><button>Add to bag +</button></form></div></article>';
}
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    try {
        verify_csrf(); $action=$_POST['action'] ?? ''; $return=safe_return($_POST['return'] ?? '', store_url($store,'cart'));
        if($action==='cart_add') { $id=(int)($_POST['product_id']??0); $s=$db->prepare('SELECT id FROM products WHERE id=? AND store_id=? AND is_active=1');$s->execute([$id,$store['id']]); if(!$s->fetch()) throw new RuntimeException('This product is not available.'); $_SESSION['cart'][$id]=min(99,(int)($_SESSION['cart'][$id]??0)+1); flash('Added to your bag.'); }
        elseif($action==='cart_update'){ foreach(($_POST['quantity']??[]) as $id=>$quantity){$quantity=(int)$quantity;if($quantity>0)$_SESSION['cart'][(int)$id]=min(99,$quantity);else unset($_SESSION['cart'][(int)$id]);}flash('Your bag has been updated.');}
        elseif($action==='cart_remove'){unset($_SESSION['cart'][(int)($_POST['product_id']??0)]);flash('Product removed from your bag.');}
        elseif($action==='coupon'){ $code=strtoupper(trim($_POST['code']??''));$s=$db->prepare('SELECT id FROM coupons WHERE store_id=? AND code=? AND is_active=1');$s->execute([$store['id'],$code]);if(!$s->fetch())throw new RuntimeException('That offer code is not active.');$_SESSION['coupon_code']=$code;flash('Offer code applied.'); }
        elseif($action==='coupon_remove'){unset($_SESSION['coupon_code']);flash('Offer code removed.');}
        elseif($action==='checkout'){
            $rows=cart_rows($db,$store);if(!$rows)throw new RuntimeException('Your bag is empty.');$name=trim($_POST['customer_name']??'');$email=filter_var($_POST['customer_email']??'',FILTER_VALIDATE_EMAIL);$address=trim($_POST['shipping_address']??'');if(!$name||!$email||!$address)throw new RuntimeException('Please enter your name, email, and delivery address.');
            $subtotal=array_sum(array_column($rows,'line_total'));[$discount,$coupon]=coupon_discount($db,$store,$subtotal);$number='ECM-'.date('ymd').'-'.strtoupper(substr(bin2hex(random_bytes(3)),0,6));
            $db->beginTransaction();$stmt=$db->prepare('INSERT INTO orders (store_id,order_number,customer_name,customer_email,customer_phone,shipping_address,subtotal,discount,total,coupon_code) VALUES (?,?,?,?,?,?,?,?,?,?)');$stmt->execute([$store['id'],$number,$name,$email,trim($_POST['customer_phone']??''),$address,$subtotal,$discount,$subtotal-$discount,$coupon['code']??'']);$orderId=(int)$db->lastInsertId();$item=$db->prepare('INSERT INTO order_items (order_id,product_id,product_name,unit_price,quantity) VALUES (?,?,?,?,?)');$stock=$db->prepare('UPDATE products SET stock=MAX(0,stock-?) WHERE id=?');foreach($rows as $row){$item->execute([$orderId,$row['id'],$row['name'],$row['price'],$row['quantity']]);$stock->execute([$row['quantity'],$row['id']]);}$db->commit();$_SESSION['cart']=[];unset($_SESSION['coupon_code']);flash('Order '.$number.' has been created. We will contact you with payment details.');header('Location: '.store_url($store,'order',['number'=>$number]));exit;
        }
        header('Location: '.$return);exit;
    } catch(Throwable $error){ if($db->inTransaction())$db->rollBack();flash($error->getMessage(),'error');header('Location: '.($route?store_url($store,$route):store_url($store)));exit; }
}

if($route==='shop') {
    $category=$_GET['category']??null; $items=products($db,(int)$store['id'],$category); public_head($store,'Shop · '.($store['name']?:'Your Store'));public_nav($db,$store);render_flash();
    echo '<main class="shop-page"><div class="page-intro"><span>THE COLLECTION</span><h1>Find your next<br><em>favourite.</em></h1></div><div class="category-tabs"><a class="'.(!$category?'active':'').'" href="'.store_url($store,'shop').'">All</a>';foreach(categories($db,$store['id']) as $cat)echo '<a class="'.($category===$cat['slug']?'active':'').'" href="'.store_url($store,'shop',['category'=>$cat['slug']]).'">'.e($cat['name']).'</a>';echo '</div>';
    if($items){echo '<div class="product-grid">';foreach($items as $item)echo product_card($store,$item);echo '</div>';}else echo '<div class="blank-state"><b>Your collection is waiting.</b><p>Add products and categories in the admin workspace, then they will appear here.</p><a class="button dark" href="admin.php?page=products">Add products</a></div>';echo '</main>';public_footer($store);exit;
}
if($route==='search'){
    $q=trim($_GET['q']??'');$items=$q?search_products($db,$store['id'],$q):[];public_head($store,'Search · '.($store['name']?:'Your Store'));public_nav($db,$store);render_flash();echo '<main class="search-page"><div class="page-intro"><span>PRODUCT DISCOVERY</span><h1>Search the<br><em>catalog.</em></h1><form class="search-form" method="get"><input type="hidden" name="r" value="search"><input type="hidden" name="store" value="'.e($store['slug']).'"><input name="q" value="'.e($q).'" placeholder="Search product names, descriptions, and categories"><button>Search</button></form></div>';if($q)echo '<p class="result-count">'.count($items).' result'.(count($items)!==1?'s':'').' for “'.e($q).'”</p>';if($items){echo '<div class="product-grid">';foreach($items as $item)echo product_card($store,$item);echo '</div>';}elseif($q)echo '<div class="blank-state"><b>No products matched that search.</b><p>Try a product name, category, or a different word from the description.</p></div>';echo '</main>';public_footer($store);exit;
}
if($route==='product'){
    $slug=$_GET['slug']??'';$s=$db->prepare('SELECT * FROM products WHERE store_id=? AND slug=? AND is_active=1');$s->execute([$store['id'],$slug]);$product=$s->fetch();if(!$product){http_response_code(404);$route='notfound';}else{public_head($store,$product['name'].' · '.$store['name']);public_nav($db,$store);render_flash();$cats=product_categories($db,$product['id']);echo '<main class="product-page"><div class="product-gallery">'.($product['image']?'<img src="'.e($product['image']).'" alt="'.e($product['name']).'">':'<span class="image-placeholder">Product image</span>').'</div><section><div class="breadcrumbs">'.implode(' · ',array_map(fn($c)=>e($c['name']),$cats)).'</div><h1>'.e($product['name']).'</h1><h2>'.money((float)$product['price']).'</h2><p>'.nl2br(e($product['description'] ?: 'Add product details in the admin workspace.')).'</p><div class="product-meta"><span>'.($product['sku']? 'SKU '.$product['sku']:'Made for your collection').'</span><span>'.((int)$product['stock']>0?(int)$product['stock'].' in stock':'Availability on request').'</span></div><form class="add-form" method="post" action="'.store_url($store,'cart').'">'.csrf_field().'<input type="hidden" name="action" value="cart_add"><input type="hidden" name="product_id" value="'.$product['id'].'"><input type="hidden" name="return" value="'.e(store_url($store,'product',['slug'=>$product['slug']])).'"><button class="button dark">Add to bag <span>+</span></button></form></section></main>';public_footer($store);exit;}
}
if($route==='cart'){
    $rows=cart_rows($db,$store);$subtotal=array_sum(array_column($rows,'line_total'));[$discount,$coupon]=coupon_discount($db,$store,$subtotal);public_head($store,'Your bag · '.($store['name']?:'Your Store'));public_nav($db,$store);render_flash();echo '<main class="cart-page"><div class="page-intro"><span>YOUR SELECTION</span><h1>Your <em>bag.</em></h1></div>';if(!$rows){echo '<div class="blank-state"><b>Your bag is empty.</b><p>Add something from your catalog when you are ready.</p><a class="button dark" href="'.store_url($store,'shop').'">Explore products</a></div>';}else{echo '<div class="cart-layout"><form method="post" class="cart-items">'.csrf_field().'<input type="hidden" name="action" value="cart_update"><input type="hidden" name="return" value="'.e(store_url($store,'cart')).'">';foreach($rows as $row)echo '<article><div>'.($row['image']?'<img src="'.e($row['image']).'" alt="">':'<span class="image-placeholder">Image</span>').'</div><p><b>'.e($row['name']).'</b><small>'.money((float)$row['price']).' each</small></p><label>Quantity <input type="number" min="0" max="99" name="quantity['.$row['id'].']" value="'.$row['quantity'].'"></label><strong>'.money((float)$row['line_total']).'</strong></article>';echo '<button class="text-button">Update bag</button></form><aside class="cart-summary"><h2>Order summary</h2><p><span>Subtotal</span><b>'.money($subtotal).'</b></p>';if($coupon)echo '<p class="discount"><span>'.e($coupon['code']).'</span><b>−'.money($discount).'</b></p>';echo '<hr><p class="total"><span>Total</span><b>'.money($subtotal-$discount).'</b></p><form method="post">'.csrf_field().'<input type="hidden" name="action" value="coupon"><input type="hidden" name="return" value="'.e(store_url($store,'cart')).'"><label>Offer code<input name="code" placeholder="Enter code"></label><button class="text-button">Apply code</button></form><a class="button dark full" href="'.store_url($store,'checkout').'">Continue to checkout →</a></aside></div>';}echo '</main>';public_footer($store);exit;
}
if($route==='checkout'){
    $rows=cart_rows($db,$store);if(!$rows){header('Location: '.store_url($store,'shop'));exit;}$subtotal=array_sum(array_column($rows,'line_total'));[$discount,$coupon]=coupon_discount($db,$store,$subtotal);public_head($store,'Checkout · '.($store['name']?:'Your Store'));public_nav($db,$store);render_flash();echo '<main class="checkout-page"><div class="page-intro"><span>SECURE ORDER REQUEST</span><h1>Complete your<br><em>order.</em></h1><p>Submit your details and the store can confirm payment and delivery with you.</p></div><div class="checkout-layout"><form method="post" class="checkout-form">'.csrf_field().'<input type="hidden" name="action" value="checkout"><label>Full name<input required name="customer_name"></label><label>Email address<input required type="email" name="customer_email"></label><label>Phone number<input name="customer_phone"></label><label>Delivery address<textarea required name="shipping_address" rows="4"></textarea></label><button class="button dark full">Place order request →</button></form><aside class="cart-summary"><h2>Order summary</h2><p><span>'.count($rows).' item'.(count($rows)!==1?'s':'').'</span><b>'.money($subtotal).'</b></p>'.($discount?'<p class="discount"><span>'.e($coupon['code']).'</span><b>−'.money($discount).'</b></p>':'').'<hr><p class="total"><span>Total</span><b>'.money($subtotal-$discount).'</b></p><small>Payments are collected by the merchant after order confirmation.</small></aside></div></main>';public_footer($store);exit;
}
if($route==='order'){
    $number=$_GET['number']??'';$s=$db->prepare('SELECT * FROM orders WHERE store_id=? AND order_number=?');$s->execute([$store['id'],$number]);$order=$s->fetch();public_head($store,'Order confirmed');public_nav($db,$store);render_flash();echo '<main class="order-page"><div class="confirmation"><span>✓</span><h1>'.($order?'Order request received.':'Order status unavailable.').'</h1><p>'.($order?'Your reference is <b>'.e($order['order_number']).'</b>. The store will contact '.e($order['customer_email']).' with payment and delivery details.':'Please check your email or contact the store.').'</p><a class="button dark" href="'.store_url($store,'shop').'">Continue shopping</a></div></main>';public_footer($store);exit;
}
if($route==='about'){
    public_head($store,'About · '.($store['name']?:'Your Store'));public_nav($db,$store);echo '<main class="about-page"><section><span>OUR STORY</span><h1>'.e($store['name'] ?: 'Your brand').'<br><em>in your own words.</em></h1><p>'.nl2br(e($store['description'] ?: 'Add your brand story in the storefront settings. This page updates automatically for shoppers.')).'</p><a class="button dark" href="'.store_url($store,'shop').'">Explore the collection</a></section><div class="about-art">'.($store['logo']?'<img src="'.e($store['logo']).'" alt="">':'✦').'</div></main>';public_footer($store);exit;
}
if($route==='notfound'){http_response_code(404);}
$bannerStmt=$db->prepare('SELECT * FROM banners WHERE store_id=? AND is_active=1 ORDER BY sort_order,id');$bannerStmt->execute([$store['id']]);$banners=$bannerStmt->fetchAll();$featured=products($db,(int)$store['id']);
public_head($store,$store['name'] ?: 'Your Store');public_nav($db,$store);render_flash();
echo '<main class="home-page"><section class="hero '.($banners?'has-banner':'').'">';
if($banners){echo '<div class="banner-track">';foreach($banners as $index=>$banner)echo '<article class="hero-slide'.($index?' is-hidden':'').'">'.($banner['image']?'<img src="'.e($banner['image']).'" alt="">':'<div class="hero-image-placeholder">Sale banner image</div>').'<div><span>FEATURED OFFER</span><h1>'.e($banner['title']).'</h1><p>'.e($banner['subtitle']).'</p><a class="button dark" href="'.e($banner['cta_url'] ?: store_url($store,'shop')).'">'.e($banner['cta_label'] ?: 'Shop now').' →</a></div></article>';echo '</div>';}else{echo '<div class="hero-empty"><div><span>YOUR STOREFRONT</span><h1>'.e($store['hero_title'] ?: ($store['tagline'] ?: 'Make room for your story.')).'</h1><p>'.e($store['description'] ?: 'Upload a hero sale banner from the admin workspace, or add your store message here.').'</p><a class="button dark" href="'.store_url($store,'shop').'">Explore products →</a></div><div class="hero-image-placeholder">Hero banner</div></div>';}
echo '</section><section class="featured"><div class="section-heading"><div><span>THE COLLECTION</span><h2>Built around<br><em>your products.</em></h2></div><a href="'.store_url($store,'shop').'">View all →</a></div>';
if($featured){echo '<div class="product-grid">';foreach(array_slice($featured,0,8) as $item)echo product_card($store,$item);echo '</div>';}else echo '<div class="blank-state"><b>Ready for your first product.</b><p>Use the admin workspace to add products, categories, images, banners, and offers.</p><a class="button dark" href="admin.php?page=products">Open admin workspace</a></div>';echo '</section><section class="story-callout"><div><span>YOUR POINT OF VIEW</span><h2>Make the template<br><em>entirely yours.</em></h2><p>'.e($store['description'] ?: 'Start with your real brand details, then keep updating every storefront section without touching code.').'</p><a href="'.store_url($store,'about').'">Read your story →</a></div><div class="story-mark">'.($store['logo']?'<img src="'.e($store['logo']).'" alt="">':'✦').'</div></section></main>';public_footer($store);
