<?php
require_once __DIR__ . '/app/layout.php';
$db=db();$store=current_store($db);$step=max(1,min(4,(int)($_GET['step']??1)));
function setup_image_or_url(string $field, string $urlField, string $existing): string { $uploaded=upload_image($field); if($uploaded)return $uploaded; $url=trim($_POST[$urlField]??''); return filter_var($url,FILTER_VALIDATE_URL)?$url:$existing; }
if($_SERVER['REQUEST_METHOD']==='POST'){
    try{verify_csrf();$action=$_POST['action']??'';
        if($action==='identity'){
            $name=trim($_POST['name']??'');$email=filter_var($_POST['email']??'',FILTER_VALIDATE_EMAIL);$password=$_POST['password']??'';if(!$name)throw new RuntimeException('Add a store name to continue.');
            $slug=slugify($name);$exists=$db->prepare('SELECT id FROM stores WHERE slug=? AND id<>?');$exists->execute([$slug,$store['id']]);if($exists->fetch())$slug.='-'.substr(bin2hex(random_bytes(2)),0,4);
            $logo=setup_image_or_url('logo','logo_url',$store['logo']);$db->prepare('UPDATE stores SET name=?,slug=?,tagline=?,description=?,logo=?,updated_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$name,$slug,trim($_POST['tagline']??''),trim($_POST['description']??''),$logo,$store['id']]);
            $hasAdmin=(int)$db->prepare('SELECT COUNT(*) FROM admins WHERE store_id=?')->execute([$store['id']]);$count=$db->prepare('SELECT COUNT(*) FROM admins WHERE store_id=?');$count->execute([$store['id']]);if(!(int)$count->fetchColumn()) {if(!$email||strlen($password)<8)throw new RuntimeException('Use an email and a password with at least 8 characters for the store admin.');$db->prepare('INSERT INTO admins (store_id,email,password_hash,name) VALUES (?,?,?,?)')->execute([$store['id'],$email,password_hash($password,PASSWORD_DEFAULT),trim($_POST['owner_name']??'Store owner')]);}
            flash('Brand identity saved.');header('Location: setup.php?step=2');exit;
        }
        if($action==='catalog'){
            $categoryNames=array_filter(array_map('trim',explode(',',$_POST['categories']??'')));$categoryIds=[];foreach($categoryNames as $name){$slug=slugify($name);$find=$db->prepare('SELECT id FROM categories WHERE store_id=? AND slug=?');$find->execute([$store['id'],$slug]);$found=$find->fetch();if(!$found){$db->prepare('INSERT INTO categories (store_id,name,slug) VALUES (?,?,?)')->execute([$store['id'],$name,$slug]);$categoryIds[]=(int)$db->lastInsertId();}else $categoryIds[]=(int)$found['id'];}
            $productName=trim($_POST['product_name']??'');if($productName){$slug=slugify($productName);$duplicate=$db->prepare('SELECT id FROM products WHERE store_id=? AND slug=?');$duplicate->execute([$store['id'],$slug]);if($duplicate->fetch())$slug.='-'.substr(bin2hex(random_bytes(2)),0,4);$image=setup_image_or_url('product_image','product_image_url','');$db->prepare('INSERT INTO products (store_id,name,slug,price,description,image,stock) VALUES (?,?,?,?,?,?,?)')->execute([$store['id'],$productName,$slug,(float)($_POST['price']??0),trim($_POST['product_description']??''),$image,max(0,(int)($_POST['stock']??0))]);$productId=(int)$db->lastInsertId();$link=$db->prepare('INSERT OR IGNORE INTO product_categories (product_id,category_id) VALUES (?,?)');foreach($categoryIds as $id)$link->execute([$productId,$id]);index_product($db,$productId);}
            flash('Catalog saved. You can add unlimited products later in the admin workspace.');header('Location: setup.php?step=3');exit;
        }
        if($action==='style'){$theme=in_array($_POST['theme']??'', ['minimal','brutalist','editorial','playful','luxe'],true)?$_POST['theme']:'minimal';$hero=setup_image_or_url('hero_image','hero_image_url',$store['hero_image']);$db->prepare('UPDATE stores SET primary_color=?,secondary_color=?,accent_color=?,theme=?,font_style=?,hero_title=?,hero_image=?,show_brand_name=?,updated_at=CURRENT_TIMESTAMP WHERE id=?')->execute([valid_color($_POST['primary_color']??'','#6D5EF2'),valid_color($_POST['secondary_color']??'','#E9E6FF'),valid_color($_POST['accent_color']??'','#F37B5B'),$theme,$_POST['font_style']==='serif'?'serif':'sans',trim($_POST['hero_title']??''),$hero,isset($_POST['show_brand_name'])?1:0,$store['id']]);flash('Storefront style saved.');header('Location: setup.php?step=4');exit;}
        if($action==='publish'){$db->prepare('UPDATE stores SET is_live=1,updated_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$store['id']]);flash('Your storefront is live and ready for customers.');header('Location: '.store_url(current_store($db)));exit;}
    }catch(Throwable $e){flash($e->getMessage(),'error');header('Location: setup.php?step='.$step);exit;}
}
$store=current_store($db);public_head($store,'Setup your store');
echo '<div class="setup-shell-php"><aside><a class="em-php-logo" href="index.php">E-Com <em>Minutes</em></a><span>STORE SETUP</span><ol>';foreach(['Identity','Catalog','Style','Go live'] as $i=>$label){$number=$i+1;echo '<li class="'.($number===$step?'active':($number<$step?'done':'')).'"><b>'.($number<$step?'✓':'0'.$number).'</b>'.$label.'</li>';}echo '</ol><p><b>Everything stays editable.</b><small>Update your storefront any time from admin.</small></p></aside><main><a class="setup-exit" href="index.php">Save & exit ×</a><div class="setup-progress"><i style="width:'.($step*25).'%"></i></div>';
if($step===1)echo '<section class="setup-stage"><span>STEP 01 / 04</span><h1>Set the brand<br><em>foundation.</em></h1><p>Use your real store details. The logo, name and story update the storefront everywhere.</p><form method="post" enctype="multipart/form-data">'.csrf_field().'<input type="hidden" name="action" value="identity"><div class="upload-box">'.($store['logo']?'<img src="'.e($store['logo']).'" alt="">':'<span>Logo upload</span>').'<label>Upload logo<input type="file" name="logo" accept="image/*"></label><input name="logo_url" placeholder="or paste a logo image URL"></div><div class="form-grid"><label>Store name<input required name="name" value="'.e($store['name']).'" placeholder="Your brand"></label><label>Owner name<input name="owner_name" placeholder="Your name"></label></div><label>Tagline<input name="tagline" value="'.e($store['tagline']).'" placeholder="A concise line about the brand"></label><label>Brand story<textarea name="description" rows="4" placeholder="What should shoppers know about your products?">'.e($store['description']).'</textarea></label><div class="form-grid"><label>Admin email<input required type="email" name="email" placeholder="you@example.com"></label><label>Admin password<input required type="password" name="password" minlength="8" placeholder="At least 8 characters"></label></div><button class="button dark">Continue →</button></form></section>';
elseif($step===2)echo '<section class="setup-stage"><span>STEP 02 / 04</span><h1>Add your first<br><em>product.</em></h1><p>One product can belong to several categories. Add as many as you need later from the catalog manager.</p><form method="post" enctype="multipart/form-data">'.csrf_field().'<input type="hidden" name="action" value="catalog"><div class="setup-product-image"><label>Product image<input type="file" name="product_image" accept="image/*"></label><input name="product_image_url" placeholder="or paste product image URL"></div><label>Product name<input name="product_name" placeholder="Product name"></label><div class="form-grid"><label>Price<input name="price" type="number" min="0" step="1" placeholder="0"></label><label>Stock<input name="stock" type="number" min="0" placeholder="0"></label></div><label>Categories<input name="categories" placeholder="e.g. New arrivals, Gifts, Home"></label><small class="hint">Separate categories with commas to attach this product to multiple categories.</small><label>Description<textarea name="product_description" rows="3" placeholder="Useful details for shoppers"></textarea></label><button class="button dark">Continue →</button><a class="text-link" href="setup.php?step=3">Skip for now</a></form></section>';
elseif($step===3){echo '<section class="setup-stage"><span>STEP 03 / 04</span><h1>Make the template<br><em>look like yours.</em></h1><p>Pick a storefront personality, color system and hero message. You can add sale banners in admin next.</p><form method="post" enctype="multipart/form-data">'.csrf_field().'<input type="hidden" name="action" value="style"><div class="theme-picker">';foreach(['minimal'=>'Minimal','brutalist'=>'Neo-brutalist','editorial'=>'Editorial','playful'=>'Playful','luxe'=>'Luxe'] as $key=>$label)echo '<label class="theme-choice '.($store['theme']===$key?'selected':'').'"><input type="radio" name="theme" value="'.$key.'" '.($store['theme']===$key?'checked':'').'><span class="theme-swatch '.$key.'"></span><b>'.$label.'</b></label>';echo '</div><div class="form-grid"><label>Primary color<input name="primary_color" value="'.e($store['primary_color']).'"></label><label>Soft surface<input name="secondary_color" value="'.e($store['secondary_color']).'"></label></div><label>Accent color<input name="accent_color" value="'.e($store['accent_color']).'"></label><label>Hero message<input name="hero_title" value="'.e($store['hero_title']).'" placeholder="The headline on your homepage"></label><div class="upload-box short"><label>Hero image<input type="file" name="hero_image" accept="image/*"></label><input name="hero_image_url" placeholder="or paste a hero image URL"></div><label class="toggle-line"><input type="checkbox" name="show_brand_name" '.($store['show_brand_name']?'checked':'').'> Show brand name beside the logo</label><button class="button dark">Continue →</button></form></section>';}
else echo '<section class="setup-stage"><span>STEP 04 / 04</span><h1>Ready for a<br><em>real storefront.</em></h1><p>Your brand settings and product catalog are connected. Preview it, then publish when it feels right.</p><div class="setup-preview" style="--brand:'.e($store['primary_color']).';--soft:'.e($store['secondary_color']).'"><b>'.e($store['name']?:'YOUR BRAND').'</b><span>Shop · About · Bag</span><h2>'.e($store['hero_title']?:($store['tagline']?:'Your storefront is ready.')).'</h2></div><form method="post">'.csrf_field().'<input type="hidden" name="action" value="publish"><button class="button dark">Publish storefront →</button></form><a class="text-link" href="'.store_url($store).'">Open preview ↗</a><a class="text-link" href="admin.php">Open full admin workspace ↗</a></section>';
echo '</main></div><script src="assets/app.js"></script></body></html>';
